- hosts: localhost
  become: no
  connection: local
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Update cache
      become: yes
      apt:
        update_cache: true

    - name: Install zsh
      become: yes
      apt:
        name: zsh
        state: present

    - name: Change user shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Install ohmyzsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh

    - name: Install nodejs and npm
      become: yes
      apt:
        name: ['nodejs', 'npm']
        state: present

    - name: Install n (Node version manager)
      become: yes
      npm:
        name: n
        global: true

    - name: Install Node.js LTS version using n
      become: yes
      shell: n lts

    - name: Start a new Zsh session
      shell: exec zsh
      ignore_errors: true
