---
- hosts: localhost
  vars:
    ssh_keys:
      - name: "proton"
        src_key: "./.ssh/proton_rsa"
        dest_key: "{{ ansible_env.HOME }}/.ssh/proton_rsa"
        src_pub_key: "./.ssh/proton_rsa.pub"
        dest_pub_key: "{{ ansible_env.HOME }}/.ssh/proton_rsa.pub"
        gist_host: "gist.github.com-proton"
      - name: "tomatoai"
        src_key: "./.ssh/tomatoai_rsa"
        dest_key: "{{ ansible_env.HOME }}/.ssh/tomatoai_rsa"
        src_pub_key: "./.ssh/tomatoai_rsa.pub"
        dest_pub_key: "{{ ansible_env.HOME }}/.ssh/tomatoai_rsa.pub"
        gist_host: "gist.github.com-tomatoai"
  tasks:

    - include_tasks: tasks/core.yml
      tags:
        - core

    - include_tasks: tasks/zsh.yml
      tags:
        - zsh

    - include_tasks: tasks/dotfile.yml
      tags:
        - update-dotfiles

    - include_tasks: tasks/install_neovim.yml
      tags:
        - nvim

    - include_tasks: tasks/node.yml
      tags:
        - node

    - include_tasks: tasks/copy_keys.yml
      tags:
        - ssh

    - include_tasks: tasks/setup_ssh.yml
      tags:
        - ssh

    - include_tasks: tasks/git-config.yml
      tags:
        - git-config

    - include_tasks: tasks/clone_macos_config.yml
      tag:
        - example

    - include_tasks: tasks/clone_tomato_frontend.yml
      tags:
        - tomato
        
    - include_tasks: tasks/clone_tomato_backend.yml
      tags:
        - tomato
        - docker-build
