- hosts: localhost
  become: true
  vars:
    source_key_proton: "./.ssh/proton_rsa"
    dest_key_proton: "{{ lookup('env', 'HOME') }}/.ssh/proton_rsa"
    source_key_proton_pub: "./.ssh/proton_rsa.pub"
    dest_key_proton_pub: "{{ lookup('env', 'HOME') }}/.ssh/proton_rsa.pub"
    source_key_tomatoai: "./.ssh/tomatoai_rsa"
    dest_key_tomatoai: "{{ lookup('env', 'HOME') }}/.ssh/tomatoai_rsa"
    source_key_tomatoai_pub: "./.ssh/tomatoai_rsa.pub"
    dest_key_tomatoai_pub: "{{ lookup('env', 'HOME') }}/.ssh/tomatoai_rsa.pub"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include_tasks: tasks/copy_ssh_keys.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfile.yml
    - include_tasks: tasks/git-config.yml