- name: Ensure utility packages are installed
  become: yes
  dnf:
    name:
      - zsh
      - vim-enhanced
      - curl
      - tmux
      - fzf
      - ripgrep
      - fastfetch 
      - jq
      - unzip
      - sway
      - grim
      - slurp
      - wl-clipboard
      - brightnessctl
    state: present
    update_cache: yes
  tags:
    - update-dotfile
