- name: Ensure utility packages are installed
  become: yes
  dnf:
    name:
      - zsh
      - vim-enhanced
      - curl
      - tmux
      - fzf
      - xclip
      - ripgrep
      - fastfetch
      - jq
      - unzip
      - sway
      - grim
      - slurp
      - wl-clipboard
      - brightnessctl
    state: present
    update_cache: yes
  tags:
    - core

- name: Add the user to the video group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: video
    append: yes
  tags:
    - core

