- name: Ensure utility packages are installed
  become: yes
  dnf:
    name:
      - zsh
      - vim-enhanced
      - curl
      - tmux
      - fzf
      - xclip
      - ripgrep
      - fastfetch 
      - jq
      - unzip
      - gcc
      - make
      - sway
    state: present
    update_cache: yes
  tags:
    - update-dotfile
