- name: Wait for apt lock to be released
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done
  become: yes
  tags:
    - node

- name: Install nodejs and npm
  dnf:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes
  become: yes
  tags:
    - node

- name: Install N
  npm:
    name: n
    global: yes
  become: yes
  tags:
    - node

- name: Install LTS version of Node
  shell: n lts 
  become: yes
  tags:
    - node

- name: Install tldr globally
  npm:
    name: tldr
    global: yes
  become: yes
  tags:
    - node
