- name: Ensure utility packages are installed
  apt:
    name:
      - vim-gtk3
      - chafa
      - bat
      - fzf
      - xclip
      - ripgrep
      - neofetch
      - jq 
      - taskwarrior
      - unzip
      - gcc
      - make
      - ripgrep
    state: present
    update_cache: yes
  tags: 
    - update-dotfiles
