- name: Ensure utility packages are installed
  become: yes
  apt:
    name:
      - vim-gtk3
      - curl
      - tmux
      - chafa
      - bat
      - fzf
      - xclip
      - ripgrep
      - neofetch
      - jq 
      - taskwarrior
      - unzip
      - gcc
      - make
      - ripgrep
      - sway
      - swaylock
      - pipewire
      - pipewire-pulse
      - wireplumber
    state: present
    update_cache: yes
  tags: 
    - update-dotfiles
