- name: Define home and username variables
  set_fact:
    home: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"

- name: Copying dotfiles to $HOME
  ansible.builtin.copy:
    src: ../env/
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
  tags: 
    - update-dotfiles
