- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Copy shared dotfiles (excluding .config)
  copy:
    src: "../env/shared/"
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  tags:
    - update-dotfiles

- name: Synchronize shared .config
  synchronize:
    src: "../env/shared/.config/"
    dest: "{{ ansible_env.HOME }}/.config"
  delegate_to: localhost
  tags:
    - update-dotfiles

- name: Synchronize environment-specific .config
  synchronize:
    src: "../env/{{ env_type }}/.config/"
    dest: "{{ ansible_env.HOME }}/.config"
  delegate_to: localhost
  when: env_type is defined
  tags:
    - update-dotfiles

- name: Copy environment-specific dotfiles (excluding .config)
  copy:
    src: "../env/{{ env_type }}/"
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  when: env_type is defined
  tags:
    - update-dotfiles

- name: Debug message if env_type is not defined
  debug:
    msg: "env_type is not defined. Only shared dotfiles were copied."
  when: env_type is not defined
  tags:
    - update-dotfiles

