- name: Ensure global Git configuration includes conditional configurations
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    line: |
      [includeIf "gitdir:~/projects/"]
          path = ~/.gitconfig-proton
      [includeIf "gitdir:~/tomatoai/"]
          path = ~/.gitconfig-tomatoai
    create: yes

- name: Create Git configuration for proton
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig-proton"
    content: |
      [user]
          name = Fabrizio Anichini
          email = fabrizioanichini@proton.me

- name: Create Git configuration for tomatoai
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig-tomatoai"
    content: |
      [user]
          name = Fabrizio Anichini
          email = fabrizio.anichini@tomatoai.it