- name: Ensure global Git configuration includes conditional configurations
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    line: |
      [includeIf "gitdir:~/projects/"]
          path = ~/.gitconfig-proton
      [includeIf "gitdir:~/tomatoai/"]
          path = ~/.gitconfig-tomatoai
    create: yes
  tags:
    - git-config

- name: Create Git configuration for Proton
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig-proton"
    content: |
      [user]
          name = Fabrizio Anichini
          email = fabrizioanichini@proton.me
      [pull]
          rebase = false
  tags:
    - git-config

- name: Create Git configuration for Tomato AI
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig-tomatoai"
    content: |
      [user]
          name = Fabrizio Anichini
          email = fabrizioanichini@tomatoai.it
      [pull]
          rebase = false
  tags:
    - git-config

- name: Set global Git configuration (fallback)
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: 'user.name', value: 'Fabrizio Anichini' }
    - { name: 'user.email', value: 'fabrizioanichini@proton.me' }
    - { name: 'pull.rebase', value: 'false' }
  tags:
    - git-config
