- name: Download latest Neovim Linux64 archive
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
  become: true

- name: Remove existing Neovim installation
  file:
    path: /opt/nvim
    state: absent
  become: true

- name: Extract Neovim archive to /opt
  unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes
  become: true

- name: Add Neovim to PATH in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$PATH:/opt/nvim-linux64/bin"'
    state: present
  become: false

- name: Clean up downloaded archive
  file:
    path: /tmp/nvim-linux64.tar.gz
    state: absent
  become: true