- name: Ensure .ssh directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '0700'

- name: Copy SSH private key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0600'
  with_items:
    - { src: "{{ source_key_proton }}", dest: "{{ dest_key_proton }}" }
    - { src: "{{ source_key_tomatoai }}", dest: "{{ dest_key_tomatoai }}" }

- name: Copy SSH public key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - { src: "{{ source_key_proton_pub }}", dest: "{{ dest_key_proton_pub }}" }
    - { src: "{{ source_key_tomatoai_pub }}", dest: "{{ dest_key_tomatoai_pub }}" }

- name: Add GitHub to known hosts
  shell: ssh-keyscan github.com >> "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"

- name: Ensure known_hosts file has correct permissions
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    mode: '0644'

- name: Start SSH agent and add key
  shell: |
    eval $(ssh-agent -s)
    ssh-add "{{ dest_key_tomatoai }}"
  args:
    executable: /bin/bash

- name: Change ownership of .ssh directory and keys
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    recurse: yes
  tags:
    - dotfiles
    - install
    - ssh