- name: Ensure .ssh directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '0700'

- name: Copy SSH private key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0600'
  with_items:
    - { src: "{{ source_key_proton }}", dest: "{{ dest_key_proton }}" }
    - { src: "{{ source_key_tomatoai }}", dest: "{{ dest_key_tomatoai }}" }

- name: Copy SSH public key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - { src: "{{ source_key_proton_pub }}", dest: "{{ dest_key_proton_pub }}" }
    - { src: "{{ source_key_tomatoai_pub }}", dest: "{{ dest_key_tomatoai_pub }}" }