- name: Start SSH agent and add keys
  shell: |
    eval $(ssh-agent -s)
    {% for key in ssh_keys %}
    ssh-add {{ key.dest_key }}
    {% endfor %}

- name: Change ownership of .ssh directory and keys
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    recurse: yes
