- name: Install ZSH
  apt: 
    name: zsh
    state: present
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Change shell to zsh for the current user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - install
    - dotfiles
    - productivity
    - zsh

- name: Install Oh-My-Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Set Zsh as the default shell and switch immediately for the current user
  ansible.builtin.shell: |
    chsh -s /bin/zsh "{{ ansible_user_id }}"
    exec /bin/zsh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
