- name: Define home and username variables
  set_fact:
    home: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install ZSH
  apt: 
    name: zsh
    state: present
  become: yes
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Get zsh path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Set Zsh as the default shell for the user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install Oh-My-Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home }}/.oh-my-zsh"
    depth: 1
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh