- name: Define home and username variables
  set_fact:
    home: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"
  tags:
    - zsh

- name: Install ZSH
  apt:
    name: zsh
    state: present
  become: yes
  tags:
    - zsh

- name: Get zsh path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false
  tags:
    - zsh

- name: Install Oh-My-Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home }}/.oh-my-zsh"
    depth: 1
  tags:
    - zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh

- name: Set Zsh as default shell
  user:
    name: "{{ username }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes
  tags:
    - zsh

- name: Display completion message
  ansible.builtin.debug:
    msg: "Zsh setup is complete and set as your default shell! Please log out and log back in for the changes to take effect."
  tags:
    - zsh