- name: Define home and username variables
  set_fact:
    home: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"

- name: Install ZSH
  apt: 
    name: zsh
    state: present
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Change shell to zsh for the current user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
  tags:
    - install
    - dotfiles
    - productivity
    - zsh

- name: Install Oh-My-Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home }}/.oh-my-zsh"
    depth: 1
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Set Zsh as the default shell and switch immediately for the current user
  ansible.builtin.shell: |
    chsh -s /bin/zsh "{{ username }}"
    exec /bin/zsh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
